sudo: required

language: node_js

node_js:
  - "8"

services:
  - docker

before_script:
  - docker --version
  - docker-compose --version

  - docker-compose up --build

script:
  - docker-compose exec node yarn coverage
