version: '3'
services:
  # Nginx reverse proxy.
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    depends_on:
      - node

  # The Node.js API.
  node:
    build: .
    depends_on:
      - mongo
    environment:
      # These env variables are necessary to let Nginx reverse proxy us.
      - VIRTUAL_HOST=api.lovvedit.com
      - VIRTUAL_PORT=44300

      # These env variables will be read from the host machine.
      - NODE_ENV
      - HOST
      - PORT
      - MONGO_NAME
      - MONGO_HOST
      - MONGO_PORT
      - EMAIL_SERVICE
      - EMAIL_URI
      - EMAIL_PASS
      - JWT_SECRET
      - LOG_LEVEL

  # The main database.
  mongo:
    image: mongo:3.5.9
    volumes:
      - mongo_data:/data/db
    deploy:
      placement:
        constraints: [node.role == manager]

volumes:
  mongo_data:
