version: '3'
services:
  # The reverse proxy
  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - node

  # The Node.js API
  node:
    build: .
    depends_on:
      - mongo
    environment:
      - NODE_ENV
      - PORT
      - MONGO_NAME
      - MONGO_HOST
      - MONGO_PORT
      - EMAIL_SERVICE
      - EMAIL_URI
      - EMAIL_PASS
      - JWT_SECRET
      - LOG_LEVEL

  # The main database
  mongo:
    image: mongo:3.5.11
    volumes:
      - ./mongo_data:/data/db
