version: '3'
services:
  nginx:
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
  node:
    command: yarn run start:dev
    volumes:
      - .:/usr/src/app
    env_file:
      - .env

  mongo:
    env_file:
      - .env
